# Model hyperparameters
inference_mode        : True
num_epochs            : 15
seed                  : 42
ckpt_save_freq        : 10


# Dataset parameters
dataset:
  path                : r'C:\temp\Dataset' #r'..\Dataset'
  train_split         : 0.8
  validation_split    : 0.1           
  test_split          : 0.1
  classes             : 2
  batch_size          : 32


Tokenizer:
  embed_dim : 384


# Model architecture
model:
  num_classes           : 2 # Assuming 2 classes (Healthy and Damaged)
  n_heads               : 12
  depth                 : 1
  input_image_size      : 224
  patch_size            : 7
  in_chanel             : 3
  p                     : 0.1
  attention_p           : 0.1


# Optimization parameters
optimizer :
  name            : AdamW
  learning_rate   : 0.001
  weight_decay    : 0.03

# Scheduler parameters
scheduler:
  name        : OneCylcle
  start_factor: 1
  end_factor  : 0.5
  total_iters : 20
